export const GET_TRANSACTIONTYPES = 'GET_TRANSACTIONTYPES';
export const GET_STORES = 'GET_STORES';
export const SET_STORES = 'SET_STORES';
export const SET_TRANSACTIONTYPES = 'SET_GET_TRANSACTIONTYPES';
export const VALIDATE_VALE_USER_FOUND = 'VALIDATE_VALE_USER_FOUND';
export const CHECK_IF_VALIDATE_PARENT = 'CHECK_IF_VALIDATE_PARENT';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const SET_TRANSACTION = 'SET_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const SET_LOADING = 'SET_LOADING';
export const SET_INVOICE_RESPONSE = 'SET_INVOICE_RESPONSE';
export const STORE_REHYDRATED_FINISH = 'STORE_REHYDRATED_FINISH';
export const SET_STATE_APP = 'SET_STATE_APP';
export const LOGOUT_APP = 'LOGOUT_APP';
export const SET_LOCAL_TRANSACTIONS = 'SET_LOCAL_TRANSACTIONS';
export const CREATE_CONCILIATION = 'CREATE_CONCILIATION';
export const DELETE_CONCILIATION_TRANSACTIONS =
  'DELETE_CONCILIATION_TRANSACTIONS';
